#!/bin/sh
# See LICENSE file for details
# prepare agent for puppet
# pass as argument the ip of the master and let the script add the details
# to /etc/puppet/puppet.conf of agent
# NOTE: This scrits supposes that puppet is already installed on your agent server

#-------------------------------------------------------------------------------
# files
#-------------------------------------------------------------------------------

# we are updating puppet config and hosts files
PPCONFIG="/etc/puppet/puppet.conf"
HOSTSFILE="/etc/hosts"

#-------------------------------------------------------------------------------
# functions
#-------------------------------------------------------------------------------

usage () {
	printf "%s [ -m PUPPETMASTER-DOMAIN PUPPETMASTER-IP ] [ -h ]\n" "$0"
}

prepare_agent () {
	echo "$ip" "$dn" >> "$HOSTSFILE"
	sed -i "/\[main\]/a \ \ \ \ $dn" "$PPCONFIG"
	dn="server = $dn"

}

#-------------------------------------------------------------------------------
# argument parsing
#-------------------------------------------------------------------------------

mflag=0

while :
do
	case $1 in
		-h)
			usage
			exit 0
			;;
		-m)
			mflag=1
			break
			;;
		*)
			usage
			exit 1
	esac
done

if [ $mflag -eq 1 ];
then
	if [ $# -ne 3 ];
	then
		usage
		printf "Not enough or too many parameters passed to\n" "$0"
		exit 1
	fi
	dn=$2
	ip=$3
	prepare_agent "$dn" "$ip"
	exit 0
fi

